### ISSUE TITLE
Stack map frames must be generated for older class file versions

### ISSUE THREAD

**Issue by andreblanke** [andreblanke/indy-obfuscator#1]
Classes compiled to target older versions of Java (prior to Java 7, class file major version <= 51) might not contain `StackMapTable` attributes required for bytecode verification. This only becomes an issue because the obfuscator needs to bump the class file major version to at least 51 in order for `invokedynamic` instructions to be usable, at which point the `StackMapTable` attribute is no longer optional.

ASM is able to generate the stack frames using `new ClassWriter(reader, ClassWriter.COMPUTE_FRAMES)` but this leads to several issues:

1. The default implementation of `ClassWriter.getCommonSuperClass(String type1, String type2)`, invoked as part of the frame computation process, operates by attempting to load both classes using `Class.forName`. The class loading attempt fails, as the obfuscator does not include the input JAR in the classpath.

    Dynamically adding the input JAR to the system `ClassLoader` appears to be hard since Java 9, if not even hacky.

    However, `ClassWriter.getCommonSuperClass` could be re-implemented without the need for class loading.
    See [rehanpadhye/JQF's SafeClassWriter.java][1] for such an implementation.

3. The `jsr`, `jsr_w`, and `ret` instructions which may appear in older bytecode [must be replaced][2], both because the JVMS suggests they are deprecated for newer class file versions, as well as due to ASM failing to compute stack frames when they are present, yielding `JSR/RET are not supported with computeFrames option`.

    The [`JSRInlinerAdapter`][3] could be used for this purpose.

[1]: https://github.com/rohanpadhye/JQF/blob/master/instrument/src/main/java/janala/instrument/SafeClassWriter.java
[2]: https://stackoverflow.com/q/37013761
[3]: https://asm.ow2.io/javadoc/org/objectweb/asm/commons/JSRInlinerAdapter.html

**Comment by kadirayk** [comment]
For now, it's fine if you support inputs with newer Java versions.
